# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScottExtension' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ScottExtension
  pod 'SNScreenShots', :path => '../'

  target 'ScottExtensionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScottExtensionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
